version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sms-assistant-db
    environment:
      POSTGRES_USER: smsadmin
      POSTGRES_PASSWORD: smspassword
      POSTGRES_DB: sms_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: sms-assistant-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://smsadmin:smspassword@postgres:5432/sms_assistant
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
